lotteon2/bitbox-frontend

src/components/chat/ChattingButton.tsx
src/components/chat/ChattingListModal.tsx
src/components/common/Header.tsx
src/components/mypage/AttendanceButton.tsx
src/components/mypage/AttendanceCalendar.tsx
src/layouts/LoginLayout.tsx
src/recoil/atoms/common.ts

💜[FIX] Warning 해결

---

package-lock.json
package.json
src/components/mypage/MyProfile.tsx
src/index.css
src/layouts/MainLayout.tsx

💜[FEAT] 마이페이지 - 회원정보 수정 모달

---

src/apis/member/member.ts
src/apis/utils/index.ts
src/components/mypage/AttendanceCalendar.tsx
src/components/mypage/MyProfile.tsx
src/index.css
src/layouts/MainLayout.tsx
src/recoil/atoms/common.ts

💜[FEAT] 마이페이지 - 사유서 제출 모달

---

src/apis/auth/oauthKakao.ts
src/components/auth/OAuthKakaoRedirect.tsx

- [ v] Feature 병합
- 서버로부터 권한, 토큰 받아서 권한, 토큰, 로그인 상태 변경 후 '/'로 navigate
- [v ] 정상 작동

💚[FEAT] set recoil states

---

src/apis/member/member.ts
src/apis/utils/index.ts
src/components/auth/OAuthKakaoRedirect.tsx
src/components/mypage/AttendanceButton.tsx
src/components/mypage/MyProfile.tsx

- ![image](https://github.com/lotteon2/bitbox-frontend/assets/81145399/ac83483f-6648-4810-822a-57498310608d)

💜[FEAT] Member - 회원정보 수정 & 입실/퇴실 완료

---

src/apis/member/member.ts
src/apis/utils/index.ts
src/components/auth/OAuthKakaoRedirect.tsx
src/components/auth/OAuthLogin.tsx
src/components/mypage/AttendanceButton.tsx
src/components/mypage/AttendanceCalendar.tsx
src/components/mypage/MyProfile.tsx
src/components/mypage/MyScoreGraph.tsx
src/recoil/atoms/member.ts

- ![image](https://github.com/lotteon2/bitbox-frontend/assets/81145399/984a0657-4029-4b11-8a49-d9da2f868f57)

💜[FEAT] Member - 성적 조회 & Member warning 해결

---

src/apis/community/community.ts
src/apis/payment/payment.ts
src/components/auth/OAuthKakaoRedirect.tsx
src/components/auth/OAuthLogin.tsx
src/components/board/BoardRegister.tsx
src/components/board/devlog/DevLogItem.tsx
src/components/board/devlog/DevLogList.tsx
src/components/board/devlog/DevLogRegister.tsx
src/components/payment/ChargeItem.tsx
src/pages/DevLogPage.tsx
src/routes/index.tsx
tailwind.config.js

- ![image](https://github.com/lotteon2/bitbox-frontend/assets/81145399/8704a282-b16a-4056-8a4a-c88d38b27865)
- ![image](https://github.com/lotteon2/bitbox-frontend/assets/81145399/38c64fb2-783a-4836-ae29-0e3acded370e)
- ![image](https://github.com/lotteon2/bitbox-frontend/assets/81145399/b9384667-5b1b-4cdf-b560-2bcbea500f70)
- ![image](https://github.com/lotteon2/bitbox-frontend/assets/81145399/c64c7d75-5638-4412-92ed-8918e59165a5)

💜[FEAT] 데브로그 게시판

---

.env
netlify.toml

💜[FEAT] netlify.toml 작성

---

src/apis/common/common.ts

💜[FIX] 이미지 업로드 경로 수정

---

src/apis/utils/index.ts
src/components/mypage/MyProfile.tsx

💜[MERGE] Member -> Main

---

src/apis/common/common.ts
src/apis/utils/index.ts

💜[FEAT] 이미지 처리

---

.env
src/apis/community/community.ts
src/apis/utils/index.ts
src/components/board/BoardList.tsx
src/components/board/community/CommunityList.tsx
src/components/board/devlog/DevLogItem.tsx
src/components/board/devlog/DevLogList.tsx
src/components/board/devlog/DevLogModify.tsx
src/components/board/devlog/DevLogRegister.tsx
src/components/chat/ChattingButton.tsx
src/components/common/Loading.tsx
src/components/main/MainDevLog.tsx
src/components/mypage/MyProfile.tsx
src/pages/CommunityPage.tsx
src/pages/DevLogPage.tsx

- ![image](https://github.com/lotteon2/bitbox-frontend/assets/81145399/426e45e0-23b1-4d3b-bcc0-4ff476ac2f3f)
- ![image](https://github.com/lotteon2/bitbox-frontend/assets/81145399/5158ca25-57b1-48d9-9392-f93c02728f2c)

💜[FEAT] 데브로그 페이지 구현

---

src/apis/community/community.ts
src/apis/utils/index.ts
src/components/board/BoardRegister.tsx
src/components/board/CategoryBadge.tsx
src/components/board/devlog/DevLogList.tsx
src/components/board/devlog/DevLogModify.tsx
src/components/board/devlog/DevLogRegister.tsx
src/components/board/review/ReviewItem.tsx
src/components/board/review/ReviewList.tsx
src/components/common/Header.tsx
src/pages/CommunityPage.tsx
src/pages/DevLogPage.tsx
src/pages/ReviewPage.tsx
src/routes/index.tsx

💜[FEAT] 게시판 선배들의 이야기 구현(진행중)

---

src/components/auth/OAuthKakaoRedirect.tsx

💚[FIX] removed loading

---

src/components/board/BoardRegister.tsx
src/components/board/alumni/AlumniItem.tsx
src/components/board/alumni/AlumniList.tsx
src/components/board/community/CommunityDetail.tsx
src/components/board/community/CommunityItem.tsx
src/pages/AlumniPage.tsx
src/pages/CommunityPage.tsx
src/routes/index.tsx

💜[FEAT] 커뮤니티 페이지 구현

---

src/apis/utils/index.ts

💜[FIX] 이미지 경로 수정

---

src/components/board/community/CommunityItem.tsx
src/pages/CommunityPage.tsx

💜[FIX] 오타 수정

---

.env
src/components/board/BoardList.tsx
src/components/board/Category.ts
src/components/board/alumni/AlumniItem.tsx
src/components/board/alumni/AlumniList.tsx
src/components/board/community/CommunityDetail.tsx
src/components/board/community/CommunityList.tsx
src/components/board/review/ReviewList.tsx
src/pages/CommunityPage.tsx

❤️[Merge] Board to Main

---

src/apis/community/community.ts
src/components/board/BoardModify.tsx
src/components/board/alumni/AlumniItem.tsx
src/components/board/community/CommunityItem.tsx
src/components/board/community/CommunityList.tsx
src/components/board/devlog/DevLogModify.tsx
src/components/board/review/ReviewItem.tsx
src/components/main/MainDevLog.tsx
src/routes/index.tsx

💜[FEAT] 게시판 수정/삭제 & 댓글 등록/삭제

---

src/components/common/Header.tsx
src/components/mypage/MyProfile.tsx
src/components/notification/NotificationDropDown.tsx

💜[FIX] Solve No AccessToken

---

src/components/chat/ChattingDetailModal.tsx
src/components/chat/ChattingListModal.tsx
src/recoil/atoms/chatting.ts

- [O] Feature 병합
- 세부사항을 항목으로 설명
- [O] 정상 작동
- [O] Conflict 발생 - 팀원과의 상의 필요

💙[FEAT] 채팅방 guest_id 및 host_id 추가

---

src/apis/community/community.ts
src/components/common/Header.tsx
src/components/mypage/MyProfile.tsx
src/components/notification/NotificationDropDown.tsx
src/recoil/atoms/common.ts

💜[FIX] Noti

---

.env
src/components/chat/ChattingDetailModal.tsx
src/recoil/atoms/chatting.ts

- [O ] Feature 병합
- 세부사항을 항목으로 설명
- [O ] 정상 작동
- [O ] Conflict 발생 - 팀원과의 상의 필요

💙[FEAT] 스톰프 주석 제거

---

src/components/board/review/ReviewList.tsx

💜[FIX] 리뷰 작성 카테고리 수정

---

src/components/board/alumni/AlumniItem.tsx
src/components/board/community/CommunityItem.tsx
src/components/board/review/ReviewItem.tsx

💜[FIX] 회원 권한 가져오기

---

src/components/board/alumni/AlumniItem.tsx
src/components/board/community/CommunityItem.tsx
src/components/board/review/ReviewItem.tsx
src/components/notification/NotificationDropDown.tsx

💜[FEAT] 게시판 댓글 작성자 표시

---

src/apis/community/community.ts
src/components/board/BoardModify.tsx
src/components/board/alumni/AlumniItem.tsx
src/components/board/community/CommunityItem.tsx
src/components/board/devlog/DevLogList.tsx
src/components/board/devlog/DevLogModify.tsx
src/components/board/review/ReviewItem.tsx
src/components/chat/ChattingButton.tsx
src/layouts/MainLayout.tsx

💜[FEAT] 회원/비회원 API 요청 구분

---

src/components/auth/LocalLogin.tsx
src/components/auth/OAuthKakaoRedirect.tsx
src/components/mypage/AttendanceButton.tsx
src/components/mypage/MyProfile.tsx
src/components/notification/NotificationDropDown.tsx

💜[FIX] console 삭제

---

.env
src/components/auth/OAuthKakaoRedirect.tsx
src/components/board/community/CommunityDetail.tsx
src/components/board/community/CommunityItem.tsx
src/components/board/community/CommunityList.tsx
src/components/mypage/MyBoard.tsx
src/components/mypage/MyProfile.tsx
src/recoil/atoms/common.ts

❤[FIX] 오류 수정

---

src/components/mypage/AttendanceCalendar.tsx

💜[FEAT] 사유서 파일 제출

---

src/apis/community/community.ts
src/components/board/alumni/AlumniList.tsx
src/components/board/community/CommunityDetail.tsx
src/components/board/community/CommunityList.tsx
src/components/board/review/ReviewList.tsx
src/components/mypage/AttendanceButton.tsx
src/components/mypage/MyBoard.tsx
src/components/payment/PaymentList.tsx

💜[FIX] 페이지네이션 설정

---

src/components/mypage/AttendanceCalendar.tsx

💜[FIX] 사유서 제출 모달 수정

---

src/components/payment/PaymentList.tsx

- [O] Feature 병합
- 세부사항을 항목으로 설명
- [O] 정상 작동
- [O] Conflict 발생 - 팀원과의 상의 필요

💙[FEAT] 결제 페이지네이션 수정

---

src/components/chat/ChattingButton.tsx
src/components/chat/ChattingDetailModal.tsx
src/components/chat/ChattingListModal.tsx

💜[FIX] 채팅 서버 Connect/Disconnect 설정

---

src/components/payment/PaymentList.tsx

💙[FIX] 페이지네이션 수정

---

src/apis/chatting/chatting.ts

💙[FIX] 채팅 관련 버그 수정

---

src/apis/chatting/chatting.ts
src/components/board/community/CommunityItem.tsx
src/components/board/review/ReviewItem.tsx

💜[FIX] 채팅방 만들기

---

src/recoil/atoms/common.ts

💙[FIX] 채팅방 수정

---

src/components/mypage/MyBoard.tsx

💜[FIX] 내 게시글 조회 오류

---

src/apis/chatting/chatting.ts

💙[FIX] 메시지 결제 수정

---

src/components/chat/ChattingDetailModal.tsx
src/components/chat/ChattingListModal.tsx
src/components/main/MainDevLog.tsx

💙[STYLE] CSS 재설정
